### ISSUE TITLE
Guest Group Not Recognized

### ISSUE THREAD

**Issue by jonstuebe** [fuel/auth#8]
I'm not sure if this has been fixed yet (maybe it has in the develop branch and i'm unaware), but I ran into an in issue where when using the acl has_access function, the guest group was not recognized as such and thus was denied access to everything including section that I had directly allowed in the config files.

**Comment by jschreuder** [comment]
This is a known limitation for which I still have to write up a solution. It has to do with the way drivers are validated, in order to check a group it needs a user but when a user wasn't logged in it won't have a group and if it doesn't have a group there's nothing to check. This will be fixed but I can't promise yet if the fix will make it into 1.0 final.

**Comment by jonstuebe** [comment]
With the help of some others I created this for an app i'm working on which seems like a decent workaround for the time being. I simply created my own class call this method instead of the default has_access method.

https://gist.github.com/991243

**Comment by jschreuder** [comment]
This is now fixed in develop.
